### ISSUE TITLE
2FA Reset

### ISSUE THREAD

**Issue by shoxxdj** [secretin/secretin-server#2]
Hello, 

When enabled 2 Factor authentication doesn't provide a rescue code.
Because of this when you loose your phone device you can't access anymore to your secretin account which has the 2FA enabled. 

I think that the application should provide a way for users to log even if they have loose their Google Authenticator ( via a rescue code ) 

Cheers !

**Comment by agix** [comment]
Server https://github.com/secretin/secretin-server/pull/3 and lib https://github.com/secretin/secretin-lib/pull/20/ ready.

Waiting for @Calyhre to review design of app https://github.com/secretin/secretin-app/pull/29

**Comment by agix** [comment]
At least ! https://github.com/secretin/secretin-app/pull/37
